#!/usr/bin/env bash
# This script installs and configures a load balancer
# Enables haproxy
sudo apt-get -y install haproxy
sudo chown $USER:$USER /etc/haproxy/haproxy.cfg
sudo chown $USER:$USER /etc/default/haproxy
sudo chmod a+w /etc/haproxy/haproxy.cfg

put_this_to_the_file=\
"
frontend load_balancer
        bind *:80
        mode http
        default_backend the_servers
backend the_servers
        balance roundrobin
        server web-01 3.84.168.103:80 check
        server web-02 100.26.250.187:80 check
"
sudo echo "$put_this_to_the_file" >> /etc/haproxy/haproxy.cfg

sudo echo "ENABLED=1" >> /etc/default/haproxy

sudo service haproxy restart
sudo apt -y autoremove
